### ISSUE TITLE
Time not displaying correctly

### ISSUE THREAD

**Issue by avonow** [titanclass/yew-chart#31] opened 2022-05-04 06:14 UTC
I have a function that creates data like this:

```
let fake_pulsewidth_data = (0..10)
    .map(|i| {
        let x_min = time_range_displayed.start;
        let x_range = time_range_displayed.end - time_range_displayed.start;
        let x = x_min + x_range / 10 * i;

        let y_min = self.series_scale.vertical.start;
        let y_range = self.series_scale.vertical.end - self.series_scale.vertical.start;
        let y = y_min + y_range / 10.0 * i as f32;
        (x, y)
    })
    .collect();
```

These are being plotted like so, where the following ranges are:
```
time_range_displayed: 2019-04-16T23:50:03.046417Z..2019-04-17T23:50:57.860785Z
self.series_scale.vertical: 0.0..10.0
```
![image](https://user-images.githubusercontent.com/53909014/166630893-a4d8986e-d0d5-4b9f-b280-aa1c45fabdfd.png)

As seen, this works correctly when the time range is quite large (>1 day).

However, when a much smaller time range is used (~ 5 mins), the datapoints are not being rendered correctly:
```
time_range_displayed: 2022-03-11T02:53:04.282941Z..2022-03-11T02:58:02.182941Z
self.series_scale.vertical: 0.0..10.0
```

![image](https://user-images.githubusercontent.com/53909014/166630845-f7ab8b49-1469-43f3-9925-1a0eee77dc52.png)

**Comment by huntc** [comment] 2022-05-05 06:14
It is unclear to me why this would be occuring. My suspicions are with the data passed into the series. I can see that the axis labels are correctly labelled, so this isn't anything obvious with the scaling functions.

If you could provide a solid reproducer than that'd be great.

**Comment by huntc** [comment] 2022-05-06 07:32
The issue is that you're coercing an i64 to an f32 and we're then naturally getting some truncation.

One possible solution is to make the `Data` type generic for types other than f32. However, this upsets a great deal of code given f32 arithmetic for screen coordinates. I'm also quite keen to stay within 32-bit registers given their performance on WASM.

An alternate solution is to normalise the data passed into a series in terms of f32 i.e. scale it down to what is required. This then implies that the scale used for the horizontal axis is different to the one used for the series... but they can represent the same span of time at the same millisecond resolution. Right now, the scale used for the series axis assumes an epoch of 1/1/1970. However, we could instead assume an epoch of the earliest start date in the data i.e. just subtract the earliest start date from all the data values. Then create a horizontal scale for the series that also has the earliest start date subtracted.

**Comment by huntc** [comment] 2022-06-20 00:55
The above suggestion feels like a reasonable solution. Closing.

**Closed as completed by huntc** 2022-06-20 00:55 UTC
